name: Update Lockfile
on:
  workflow_dispatch: # Manually trigger the workflow
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Commit updated lockfile
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add bun.lockb # or package-lock.json
          git commit -m "Update lockfile"
          git push
